version: '3'
services:
  laravel_app:
    image: bitnami/laravel:8-debian-10
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: UNAmuychingona123.   # Tu contraseña actual de root
      MYSQL_USER: mike                      # Nuevo usuario
      MYSQL_PASSWORD: UNAmuychingona123.       # Contraseña para el nuevo usuario
      MYSQL_DATABASE: forum                 # Nombre de la base de datos
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: mike
      PMA_PASSWORD: UNAmuychingona123.
    ports:
      - "8083:80"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8084:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
